apiVersion: v2
type: application
name: kube-prometheus-stack
version: 0.0.0    # unused
appVersion: 0.0.0 # unused
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 12.8.1
